version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
      - ./data/dblp.json:/data/db/dblp.json
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"  # Port de l'interface web de Mongo Express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      - mynetwork
    # command: sleep 5 && mongo-express

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork

volumes:
  mongodb-data:
    name : mongodb-data